### ISSUE TITLE
Check out autotest/docker-autotest when cache copy unavailable

### ISSUE THREAD

**Issue by cevich** [cevich/autotest-docker-enabled-product-testing#52]
Ref: https://github.com/cevich/autotest-docker-enabled-product-testing/pull/51#discussion_r77683311

```yaml
 # git repos: autotest and autotest-docker. update=no means "chill": it
 # lets us modify files in the repos without Ansible barfing on future
 # runs. If you ever want to update, just rm -rf the checkout manually.
 - name: install autotest
    git: repo=https://github.com/autotest/autotest.git
        dest={{ destdir }} update=no recursive=no

 - name: install autotest-docker
   git: repo=https://github.com/autotest/autotest-docker.git
        dest="{{ destdir }}/client/tests/docker" update=no
```
