### ISSUE TITLE
Fedora/Fedora Atomic testing container image needs python

### ISSUE THREAD

**Issue by cevich** [cevich/autotest-docker-enabled-product-testing#94]
Stick a ``dockerfile`` somewhere that's accessible by URL:

```
FROM docker.io/fedora:latest
RUN dnf install -y python
```

Then update ``group_vars/fedoratomic/autotested.yml`` with:

```
...
docker_autotest:
    test_image:
        host:
        user:
        name: fedora_docker_autotest
        tag: latest
        build_url: http://url.of.docker.file/path/dockerfile
```

An alternative is to have the image built by docker's build system (which requires a repo + dockerfile anyway)
